### ISSUE TITLE
Support Tabs

### ISSUE THREAD

**Issue by baronfel** [baronfel/fsharp-lang-suggestions-final#104]
# Support Tabs [13660647] #

**Submitted by Anonymous on 4/29/2016 12:00:00 AM**  
**11 votes on UserVoice prior to migration**  

Don't force a code style upon users. Tabs can work perfectly well in whitespace-sensitive languages - see python or haskell - and many people prefer them.
Forcing users to use your style just comes across as petty and picky: not the impression you should be giving. Disappointing to see a promising language hamstrung by narrow-minded design decisions.

## Response ##
** by fslang-admin on 6/2/2016 12:00:00 AM **

Declined, per comments below. F# is a whitespace sensitive language and the general consensus is that TABs are not a good iddea in whitespace sensitive languages given the current status of editors
Don Syme, F# Language Evolution

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/13660647)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-13660647-support-tabs.md#comments)

**Comment by SpocWeb** [comment]
This is really too bad. Many developers don't like to rely on any specific editor and allowing for Tabs is easy to implement. Only mixing Tabs and Spaces should result in an error similar to what Python linters report. I wonder where this 'general consensus' is documented. This issue has not been resolved in the last 40 years. 
Sorry for nagging, but I think the future is in using more Tabs not fewer. Please see what is possible here: http://nickgravgaard.com/elastic-tabstops/ 
Elastic Tab-Stops allow to robustly structure Lines so that similar code becomes table-like and easier to grasp. This Feature has already been added to many Editors like Notepad++ and even Visual Studio.

**Comment by matthid** [comment]
> I wonder where this 'general consensus' is documented. This issue has not been resolved in the last 40 years.

It is resolved for F#, you can only use spaces ;)

**Comment by abelbraaksma** [comment]
I think the problem is that it is impossible to have only tabs (there will always be spaces, i.e. for outdenting). That means that the parser will have to decide how large a tab is to properly know its meaning. And since that's impossible to deterministically determine, I can only agree to the choice made here, which removes a lot of potential ambiguity and misunderstandings over code.

That said, editors, including the ones you mention, are perfectly capable of inserting a bunch of spaces when you use the tab key. There's nothing that forces you to use a certain editor, CBS editors, including Notepad++ can auto indent with spaces.

As a benefit, your code will look the same regardless where it is shown, on a web page, in print, in someone else's editor. If you ever need to share code, you know that tabs are a bad choice. I've been there, I loved tabs, until I changed editors and was going slightly mad.

Luckily, for F# the 'holy war' on tab vs spaces has already been fought, and we all use the same.
