### ISSUE TITLE
respect multi-line triple quoted strings indentation

### ISSUE THREAD

**Issue by baronfel** [baronfel/fsharp-lang-suggestions-final#20]
# respect multi-line triple quoted strings indentation [11046804] #

**Submitted by George on 12/10/2015 12:00:00 AM**  
**1 votes on UserVoice prior to migration**  

It would be useful if the starting position of a multi-line triple quoted string could set the starting position of the content when it is the first non-whitespace character on it's source line. Additionally, when it is followed only by source level whitespace character, then the content is presume to actually start on the next line, indented of course. If non-whitespace characters occur prior to the indent point, then it may be flagged as a syntax error, however, EOL characters would be retained to capture lines.
Perhaps a new symbol could be used other than triple quotes...perhaps quadruple quotes: """"

## Response ##
** by fslang-admin on 12/15/2015 12:00:00 AM **

This would be a breaking change
A new symbol may be possible.
Don Syme
F# Language and Core Library Evolution

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/11046804)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-11046804-respect-multi-line-triple-quoted-strings-indentat.md#comments)

**Comment by njlr** [comment]
I was unable to find the original comments on this, but it appears to have been declined as a breaking change to `"""`. 

However, would a _new_ way to quote that does support this be feasible? I find large multi-line strings a very common occurrence in unit-tests, and this could enhance readability. 

Many of the complications other languages might have implementing this do not apply to F# due to the strict indentation rules and lack of tab characters. 

I also think it fits nicely with the "shape" of F# code, which visually flows down and right like a tree. :slightly_smiling_face:  

**After**

```fsharp
let text =
    |"""abc
        def
        ghi"""
```

**Before** 

```fsharp
let text =
    """abc
def
ghi"""
```

_or..._

```fsharp
let text =
    "abc\n"
    + "def\n"
    + "ghi"
```

_or..._

```fsharp
let text =
    [ "abc"
      "def"
      "ghi" ]
    |> String.concat "\n"
```




C# discussion: https://github.com/dotnet/csharplang/issues/2176 and https://github.com/dotnet/csharplang/issues/4013

**Comment by joprice** [comment]
Perhaps a standard library function could help as well like scala's `stripMargin`, which I used to use extensively. It uses pipes to delimit the start of the indentation https://docs.scala-lang.org/scala3/book/string-interpolation.html#the-s-interpolator-s-strings

```scala
println(s"""name: "$name",
           |age: $age""".stripMargin)
```

That can of course be written as an extension. A github search turned up a few people who have found it useful such as this example  https://github.com/yukibonji/websharper.pouchdb.samples/blob/8ee4aafc6f1f1c6160ed03ab307af42fba4edfac/WebSharper.Samples.PouchDB/Utils.fs#L23-L34.

**Comment by Martin521** [comment]
Yes, a function makes more sense.
I have felt the wish for such a feature myself a number of times.
However, like often, once you look deeper into it, you find that it is not that easy. The different use cases have different requirements and a lot of details must be considered.

- In the above example, a margin indicator (`|`) makes sense. For the typical unit test mentioned earlier that is less desirable.
- Special handling of the first and last line may be useful, again depending on the use case.

For the use case of specifying code for unit testing, I have experimented with the following.

```FSharp
/// This function splits the input string into lines, removes the first line, determines the indentation
/// (number of leading spaces) of the next line, removes that many spaces from the beginning of all
/// lines, and removes trailing spaces from all lines. It finally re-concatenates the lines to a string.
let unindent (s: string) =
    let lines = s.ReplaceLineEndings().Split(System.Environment.NewLine)
    if lines.Length < 2 then invalidArg "s" "expected an empty first line and at least one next line"
    let indentWidth = lines[1].Length - lines[1].TrimStart().Length
    let rec unindentLine width i (line: char seq) =
        if width = 0 then (line |> Seq.toArray |> System.String).TrimEnd()
        else
            match Seq.tryHead line with
            | Some ' ' -> unindentLine (width - 1) i (Seq.tail line)
            | None when i = lines.Length - 2 -> ""
            | _ -> invalidArg "s" $"expected {indentWidth} blanks to unindent in line {i + 1}"
    lines |> Array.tail |> Array.mapi (unindentLine indentWidth) |> String.concat System.Environment.NewLine
```

So that I can do
```FSharp
let myTest() =
    unindent """
        module A =
            type B = int
        module C = ()
    """
    |> FSharp
    |> compile
    |> shouldSucceed
```

This might be useful in a test utilities library.
But I don't think it can become a language feature or a core lib function.
