### ISSUE TITLE
Allow pattern matching on ranges

### ISSUE THREAD

**Issue by baronfel** [baronfel/fsharp-lang-suggestions-final#264]
# Allow pattern matching on ranges [6027309] #

**Submitted by Patrick Q on 6/9/2014 12:00:00 AM**  
**19 votes on UserVoice prior to migration**  

It would be quite useful to allow pattern matching on ranges as in the following:
let find x =
match x with
| 42 -> "aaa"
| 150 .. 180 -> "bbb"
| 222 .. 333 -> "ccc"
| _ -> "zzz"
While one can use guards or active patterns to provide equivalent functionality, it would be quite useful and result in cleaner code if pattern matching on ranges was natively supported.

## Response ##
** by fslang-admin on 6/20/2014 12:00:00 AM **

I’m declining this because a general mechanism (active patterns) already exists that achieves the desired result. In F# 2.0 we decided to add the more general mechanism and remove special cases such as character range patterns (present in OCaml).
Language design is always a tradeoff, and adding new special syntactic cases for this case doesn’t seem appropriate. For example, we would have to consider ranges of other types including floating point numbers, decimals, user-defined numeric literals etc.
Don Syme, current BDFL for the F# Language Design

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/6027309)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-6027309-allow-pattern-matching-on-ranges.md#comments)

**Comment by tats-u** [comment]
C# 9 (2020-11) includes [the relational pattern](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/patterns3#relational-patterns).

The transformation algorithm is complex (binary search?): https://sharplab.io/#v2:D4AQDABCCMB0AqBTAHgFwNwFgBQIDMUATBAMIQDeOE1UBMAbBAEYD2LANhAJIDOJAUgGkAFACUArgDtEEAMYAHAJQUqNNSADsc+bABqAQ3biZASx4RVaqxAB8AXghhk0aGEj7JAEwgAeB05cAM0DLaxoWACdHZEIwfQBOULCISNt/GLxCeIgPbz9owkz9JLDU+wL6PHcvX3TCSo0S6zK6+gAOfRya/Kd6tpDsZLUWgsQ26ry6xHjEwaHqEd7ppi7J0cC8JqtFmMC3VdqCwM8AVi3hqPLe4InDpyq8RHPwy/SqgBZoA57kKvj6Z4LV7RP7ZXJ3X5gYKAlLA+6uE7fN7QQgDeZAtIg6B4L7gn44tpPObzHY4+K3fHQRBnYlDUlUwJIkGEKkw0mEWJM+6Ed6NWnJdknCnpfTvNqyNlw5Ci8lc6XvWQA/mlKUJejC6IJDQS5XNVWyfZ49KeDT6Ta67ZSk1MDVOE2KyWYu3alZG6ImwJMR1XZCBcm2336aEWi5O32IVxywIR2bo2Fh6NVKPUwje9LRk7vZP0JVxnbR9rZr0hl4Jva47rpz1EvNS4KyYhupz1vm1suyTpN32BWRo9H546NyvRYImtMj46d4fN446ts+4KIAOL3P9uvRtpR6M1tdh6D0aMB/fR97jgIHvZy4+BaBn5waNxHtoaQKt3c+6BtcZP2SnO+f3tGS7T9PDANp/yDS9gMg8153SaBIMRaDgmLODogQ0cr0gncSSlaAbUNadnCYFFUxLDEAhIzJ/xIoUr1osi20o6AThpNDmPoLNgJI+g31wvcSIfejUVQ994M8Kojwkk5V34j8JPVK8JI0WS6SiAJAliMBHQ02JGLE9DNMjYCjNjAzdPwq9NMIHC1L3TSkxMwpb3I+NdLwPi7Pc0S5PgzT3iPfzwNcnZoE0xSnPoNjzJiR8AzwYJjiwWkAF8cBSoA

You cannot do the same thing as F#. This is why I think F# is less useful compared to C#.
We can borrow the logic from Roslyn (the official C# compiler written in C#).

OCaml is now tracking the same issue since 2019: https://github.com/ocaml/ocaml/issues/8504

**Comment by Happypig375** [comment]
@tats-u See https://github.com/fsharp/fslang-suggestions/issues/968#issuecomment-764636595

**Comment by tats-u** [comment]
@Happypig375 No. The level of the active pattern is too low. We want the F# compiler to write binary search ILs automatically as Roslyn can. The active pattern looks like the pointer syntax in C seen from Rust.

**Comment by Happypig375** [comment]
@tats-u Optimizing this switch to a binary search assumes that all the cases are hit equally compared to sequential comparison which is better when you have a "happy path" and lots of special cases. Deciding that binary search is the best option can be done explicitly with code generation tools instead of by the compiler implicitly?

**Comment by tats-u** [comment]
C# is better at code generation support by Source Generator. If you want to generate code automatically you should use C# instead. F# for C# should be C for assembler. F# tends to generate less optimized code than C#, so F# should aim at moderate performance with simpler syntax. I don't know how Rust optimize ranges joined with `|`.

**Comment by Happypig375** [comment]
Well, it also doesn't have to _be_ a pattern per se. The compiler can detect usages of built-in comparison operators and `||` then optimize code that read like
```fs
cp >= 0x1100 && cp <= 0x11ff
|| cp = 0x20a9
|| cp >= 0x2329 && cp <= 0x232a
|| cp >= 0x2630 && cp <= 0x2637
|| cp >= 0x268a && cp <= 0x268f
|| cp >= 0x2e80 && cp <= 0x2e99
|| cp >= 0x2e9b && cp <= 0x2ef3
|| cp >= 0x2f00 && cp <= 0x2fd5
|| cp >= 0x2ff0 && cp <= 0x303e
|| cp >= 0x3041 && cp <= 0x3096
|| cp >= 0x3099 && cp <= 0x30ff
|| cp >= 0x3105 && cp <= 0x312f
|| cp >= 0x3131 && cp <= 0x318e
|| cp >= 0x3190 && cp <= 0x31e5
|| cp >= 0x31ef && cp <= 0x321e
|| cp >= 0x3220 && cp <= 0x3247
|| cp >= 0x3250 && cp <= 0xa48c
|| cp >= 0xa490 && cp <= 0xa4c6
|| cp >= 0xa960 && cp <= 0xa97c
|| cp >= 0xac00 && cp <= 0xd7a3
|| cp >= 0xd7b0 && cp <= 0xd7c6
|| cp >= 0xd7cb && cp <= 0xd7fb
|| cp >= 0xf900 && cp <= 0xfaff
|| cp >= 0xfe10 && cp <= 0xfe19
|| cp >= 0xfe30 && cp <= 0xfe52
|| cp >= 0xfe54 && cp <= 0xfe66
|| cp >= 0xfe68 && cp <= 0xfe6b
|| cp >= 0xff01 && cp <= 0xffbe
|| cp >= 0xffc2 && cp <= 0xffc7
|| cp >= 0xffca && cp <= 0xffcf
|| cp >= 0xffd2 && cp <= 0xffd7
|| cp >= 0xffda && cp <= 0xffdc
|| cp >= 0xffe0 && cp <= 0xffe6
|| cp >= 0xffe8 && cp <= 0xffee
|| cp >= 0x16fe0 && cp <= 0x16fe4
|| cp >= 0x16ff0 && cp <= 0x16ff1
|| cp >= 0x17000 && cp <= 0x187f7
|| cp >= 0x18800 && cp <= 0x18cd5
|| cp >= 0x18cff && cp <= 0x18d08
|| cp >= 0x1aff0 && cp <= 0x1aff3
|| cp >= 0x1aff5 && cp <= 0x1affb
|| cp >= 0x1affd && cp <= 0x1affe
|| cp >= 0x1b000 && cp <= 0x1b122
|| cp = 0x1b132
|| cp >= 0x1b150 && cp <= 0x1b152
|| cp = 0x1b155
|| cp >= 0x1b164 && cp <= 0x1b167
|| cp >= 0x1b170 && cp <= 0x1b2fb
|| cp >= 0x1d300 && cp <= 0x1d356
|| cp >= 0x1d360 && cp <= 0x1d376
|| cp = 0x1f200
|| cp = 0x1f202
|| cp >= 0x1f210 && cp <= 0x1f219
|| cp >= 0x1f21b && cp <= 0x1f22e
|| cp >= 0x1f230 && cp <= 0x1f231
|| cp = 0x1f237
|| cp = 0x1f23b
|| cp >= 0x1f240 && cp <= 0x1f248
|| cp >= 0x1f260 && cp <= 0x1f265
|| cp >= 0x20000 && cp <= 0x3fffd
```
to use binary search. It is not necessary to introduce a pattern syntax just for this?

C# doesn't optimize for the expression equivalent of the pattern you showed -
https://sharplab.io/#v2:D4AQDABCCMB0AqBTAHgFwNwFgBQIDMUATBAMIQDeOE1UBMAbBAEYD2LANhAJIDOJAUgGkAFACUArgDtEEAMYBKClRoqAbgEMATnIAOEALxzYANXXtxiLNhUqQAdgg5ZegHyGwyaNDCQAZL90IAB53T2gAM3CcYGBA/VDCMHUATmjY5wg3CA9CPEJkiH9AkOzkXMJ1NMCsnPo8PwCMktq8OyqMmrL6AA51Qsa9Zq7uqOwY6oTEbobiyeTUsfTXOaZ+2dLCRHC8duWN8J81poTwgBMAVl3Mk4OjwdD6vEQrzvqAFmg74IewZPoXn7zL5DeqRAGlPDec7Ah7QQijcYdWGQmEQ6DdZ6LCZo5IzY5oxCXLFIgnhVEePLQTGIvYUwiJcnIPJvNrE2lMwjnPH3UrqN7dWTgjx83GMvmyf5s668v7c74yuyCqWddSyQ5FfEeU52dQ7ZWhbVMOVDbUSoXIU2rDU8rV2cJMc3hXHG0LhdRg/WlcKIbyM73QBY06Ueb31P2EwiOwlvcP0SVBzrenqxh2ekMHT7W+XppjUpbB5CRWTELNDIushOu8KyPqlquyBH5xNnEsDbOFs4VptV061ttls5Kyte70ukeIePd8fdP3evPYjzQeijxlL71vc1r2510pb6Cbuw+MeL7p2rsLzzdabHy+yC6bgWRVfdU5gbqb93b/uhaCfvXDxdP2hHdAMiVMAM8T9TlXT95xJRcjXVb9dyYOFIyleIUOgPJN1QrlVzw9Cg0whDoHOIkIOgVD6BjEDPGo894Po6BDwI+FwKnRdTnqG9oG485JwvPi8HoXjuLsQSMhIzxwkSMArmkiJEiIziZMIX06KUgNN1kqjV1kzYdNyXjZMhBSf1Mxi9EU0yOKE2S3hMwh+SM0T9MIegKNUuSkPWClIjOKwVAAXxwYKgA

but there is no reason for it not to do this.

**Comment by tats-u** [comment]
> to use binary search. It is not necessary to introduce a pattern syntax just for this?

Does it not conflict with the short circuit? You have to disable this optimization in Debug build to hide it because it seems likely to adversely affect step execution. C#'s `is` seem to work with Debug mode.

**Comment by Happypig375** [comment]
@tats-u Debug mode is supposed to be less optimized, and there's also nothing preventing the entire statement to still generated optimized lookup in Debug mode without inserting debug points inside the short-circuit operators.
