### ISSUE TITLE
Bottom type

### ISSUE THREAD

**Issue by baronfel** [baronfel/fsharp-lang-suggestions-final#349]
# Bottom type [6586873] #

**Submitted by Janek Paw on 10/20/2014 12:00:00 AM**  
**6 votes on UserVoice prior to migration**  

Bottom type
Bottom type for all types. Allows you to implement usefull functions like unimplemented (see scala ???)

## Response ##
** by fslang-admin on 2/4/2016 12:00:00 AM **

Thanks for the suggestion. Declined per my comment below.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/6586873)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-6586873-bottom-type.md#comments)

**Comment by TysonMN** [comment]
Those links are dead and the [WayBack Machine from Internet Archive](https://web.archive.org/) doesn't have a copy of either one.

**Comment by cartermp** [comment]
See here https://github.com/fsharp/fslang-suggestions/blob/d48c35ce216e2bff148937ec028ad61e5c273fdf/archive/suggestion-6586873-bottom-type.md#comment-by-don-syme-on-242016-60800-pm

Instructions for viewing are in the repo's README

**Comment by TysonMN** [comment]
Inlining the linked text:
> #### Comment by @dsyme on 2/4/2016 6:08:00 PM
> We considered this for F# 1.0 but decided to stick to the OCaml way of just using a type variable. We won't revisit that decision at this point

**Comment by TysonMN** [comment]
For those of us that are not so familiar with OCaml, what is "the OCaml way of just using a type variable", especially when  translated into F#?

**Comment by Happypig375** [comment]
I think it's a
```fs
let wip<'T> = raise (new NotImplementedException())
let default<'T> = Unchecked.defaultof<'T>
```

**Comment by TysonMN** [comment]
I am not following.  Can you elaborate @Happypig375?

**Comment by Happypig375** [comment]
`'T` is the "type variable". When you make a value generic, it effectively becomes a property (though the compiled form is a method taking zero arguments) where the return type is inferred from where it is used.

**Comment by CarstenKoenig** [comment]
> I am not following. Can you elaborate @Happypig375?

just my take on it:

one usecase of bottom is to indicate that somthing should/cannot happen - for example `Result<String, Bottom>` might indicate that there should be no error here.

Not when you have an bottom/empty type (say as Haskell has) then you should either have an `absurd : Bottom -> 'a` function so that you can pattern-match:

```
match myResult with
| Ok res -> res
| Err bot -> absurd bot
```

or you maybe extent the pattern matching mechanism/syntax so that it's ok with empty/bottom cases

```
match myResult with
| Ok res -> res
| Err Bottom
```

I think what the comment by D. Syme  means is that they choose yet another apporach: you give back a generic result - let's say you have a function `doSomethingCannotFail : MyParams -> Result<String, 'a>` this is now generic and so you have the `absurd` acutally *baked in*:

```
match doSomthingCannotFail myParams with
| Ok res -> res
| Err bottomRes -> bottomRes
```

you see as you claimed your function is generic in the error-parameter you can actually choose to be whatever you want - for example the same type as the Ok-parameter and if you ignore stuff like `failwith`, `defaultOf`, infinite-loops, ... (if you don't ignore such things then every guarantee you get with types is out of the window) you cannot actually implement `doSomethingCannotFail` in a way that will produce an `Err`

---

As I said: not sure I got your question or the context right, but this is my take on trying to explain it

**Comment by pblasucci** [comment]
FWIW...  the explanation given by @CarstenKoenig is exactly how I interpreted the comment by @dsyme (and, indeed, my understanding of the overall discussion).

**Comment by abelbraaksma** [comment]
This is also how `raise` is implemented: it's a function that never returns, and by using generics, it's return type matches any type.

The concept of `Bottom` in other languages is similar, but not the same. It's a type that has no instances and no members, and can be considered to derive from any other type (is "an instance of", if you could create an instance). Since it cannot be instantiated, it's only useful where you don't expect a function to return. Likewise, I don't think you can match on that type itself, since it has no instance to ever match.

**Comment by TysonMN** [comment]
> It should be noted that a non-instantiable type is F# is easy to construct (use two conflicting generic constraints)...

This gives me an idea.  Every reference type has `null` as a value, so start with a value type.  Then implement the default (and only) constructor by throwing an exception.  This type has no values.  This reminds me of [Wikipedia's description of bottom in Haskell](https://en.wikipedia.org/wiki/Bottom_type#In_programming_languages:~:text=Since%20Haskell2010%2C%20Haskell%20supports%20empty%20data,therefore%20it%20never%20returns%20an%20answer.).

**Comment by abelbraaksma** [comment]
> This type has no values.

I mean, has no instance, right? But technically that's not exactly true, the CLR will create an instance and then throw an exception. But functionally that seems to be what you're after, except for the very important property of `Bottom` to be a leaf type. That behavior can only be mimicked with inferred generics (as is currently done).

You could get the same behavior by creating a factory method `Bottom.create ()` that merely throws, then you get the type morphing automatically. But tooltips won't show 'Bottom'...

**Comment by TysonMN** [comment]
> > This type has no values.
> 
> You mean, has no instance, right?

Yes.  Sorry for being unclear.  I was using the name for this concept from type theory instead of the name in .NET/F#.

I think of the bottom type as having two properties:
1. no values/instances
2. subtype of every other type

Since F# doesn't depend very much on inheritance, I was just trying to achieve the first property.  My impression is that the "OCaml way of just using a type variable" is only attempting to achieve the second property.

**Comment by CarstenKoenig** [comment]
> I don't think you can match on that type itself, since it has no instance to ever match.

AFAIK you want to be able to match on every type including `Bottom` - it seems strange to exclude a *special* type from this basic syntactic tool (I'm really glad F# replaces that stupid `void` with `unit`)

There is a correspondence between types/programs(values) and logic and there (a bit simplified) *Bottom is your False*  and as *functions are implications* `absurd : Bottom -> 'a` is more or less what you know as ["from false follows everything"](https://en.wikipedia.org/wiki/Principle_of_explosion)

if there will never by a value of this thing it's safe for me to say "if you give me a bottom value I give you back ..." - it will never happen ... of course in F# it can happen but it happens with an exception or an infinite-loop or by magically pulling out a default-value - probably `null` - and that's why we cannot have nice things (type level guarantees, proofs for free, ..) in F#

**Comment by abelbraaksma** [comment]
> it seems strange to exclude a special type from this basic syntactic tool

I was musing. On the basis that `Bottom` cannot exist, a match on that type can never succeed. I honestly don't know if haskell or other languages support this.

Naturally, you can match on any type right now, even a type that cannot be created, be it a DU or a type pattern.

**Comment by CarstenKoenig** [comment]
Depends on the language and how you express such an Bottom-Type.

If you take Haskell (ok let's say GHC) you can have data declarations without data-constructors and there is pattern matching syntax for those.

Here is an [example of a `Void` type and an `absurd` function demonstrating that](https://hackage.haskell.org/package/base-4.14.0.0/docs/src/Data.Void.html#absurd)

And I think this approach is rather popular ([here is a similar definition in Agda](https://agda.github.io/agda-stdlib/Data.Empty.html))

---

overall the question is how useful it is to think about an `Bottom` type in F# if there are no guarantees at all?

Personally I think those are good ideas and useful to play with and learn about (although I would go to a language supporting this more directly) but it's nothing I'd like to have in my code-base just to be fancy (same with things like `IO` or modeling via free monads etc.)

The mentioned *workaround* (it's really more like a isomorphic representation at least on the behavior side) with the generic parameter is much more *idiomatic* and we don't have to introduce anything new.

Only problem with that it seems much easier for folks (me included) to think in terms of data and concrete type abstractions instead of the deeper encodings like with the type-parameters here - So we should teach this way of thinking way more IMO.

That's why I really enjoy this conversation.

**Comment by abelbraaksma** [comment]
> (it's really more like a isomorphic representation at least on the behavior side)

Exactly :) 

> with the generic parameter is much more idiomatic and we don't have to introduce anything new

Totally agreed. There's no use case for such type in the sense that there's already an idiomatic way to express such cases. But I think we're all in agreement here, it's fun to have the discussion, but I don't think anyone wants to reopen this to allow this concept.

**Comment by TysonMN** [comment]
> ...it's fun to have the discussion, I don't think anyone wants to reopen this to allow this concept.

Oh, yes.  I am here for the fun and interesting discussion too.  I never expected so many people to join.  I love it.  My intention was and still is to understand Don's original comment, not crique it or disagree with it.

Given that F# doesn't have a type that has both of the properties of the bottom type, I think it is interesting to see how close we can get to achieving either property individually or both properties simultaneously.

**Comment by abelbraaksma** [comment]
> I think it is interesting to see how close we can get to achieving either property individually or both properties simultaneously.

1. A type that cannot be instantiated

    ```f#
    type Bottom<'T when 'T : not struct and 'T : unmanaged> =
        | Bottom of 'T

        static member create() = Bottom(Unchecked.defaultof<_>)
    ```

    Using `Bottom.create()` will, however, throw FS1202, because the ambiguity cannot be resolved.

2. A normal non-instantiable type

    ```f#
    type Bottom =
        // will return null
        static member create() = Unchecked.defaultof<Bottom>
    ```

    You cannot create `Bottom` the normal way as it does not have public constructors. But this type can be used in normal code as it resolves just fine. However, property (2) cannot be resolved here, or anywhere else, as "a type that inherits from everything" cannot exist in CLR.

3. Using generics

    ```f#
    type Bottom =
        // will never return, but implies null or zero for any type
        static member create(): 'T = 
            exn "Unreachable code" |> raise 
            Unchecked.defaultof<'T>
    ```

    This method uses the same method as `raise` and comes close to satisfying property (2) through isomorphism. However, as noted before, the CLR does not allow a type like `Bottom`, so this is as close as one can get (I think).

**Comment by CarstenKoenig** [comment]
> My intention was and still is to understand Don's original comment...

Did my comment up there help? If not give me a hint on where it was unclear and I try to improve on it.

**Comment by TysonMN** [comment]
> 1. A type that cannot be instantiated
>    ```fsharp
>    type Bottom<'T when 'T : not struct and 'T : unmanaged> =
>        | Bottom of 'T
>    
>        static member create() = Bottom(Unchecked.defaultof<_>)
>    ```
>    
>    Using `Bottom.create()` will, however, throw FS1202, because the ambiguity cannot be resolved.

By "throw", you mean causes compiler error FS1202, right?

As a sanity check, the following code shows that this type can be the return type of a function that never returns.
```fsharp
let neverReturns () : Bottom<_> =
  while true do
    ()
  Unchecked.defaultof<_>
```

If I would have had the idea to make a generic type like this, then looking at the [list of generic constraints](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/generics/constraints), I would have tried to pair the constraints `not struct` and `struct` together.
```fsharp
type Bottom<'T when 'T : not struct and 'T : struct> = Bottom of 'T
```

However, this gives compiler error FS0043.
> The constraints 'struct' and 'not struct' are inconsistent

If the constraints `not struct` and `unmanaged` are also inconsistent, then it seems like the F# compiler could also assign error FS0043 to that type.  It current doesn't though.

**Comment by abelbraaksma** [comment]
>  it seems like the F# compiler could also assign error FS0043 to that type. It current doesn't though.

It's an open bug that certain combinations are illegal but don't raise that compile error.

**Comment by TysonMN** [comment]
For now! ;)

That issue is https://github.com/dotnet/fsharp/issues/9777

**Comment by abelbraaksma** [comment]
@TysonMN, at least one "illegal" combination will remain allowed for backwards compat reasons. As mentioned in that issue, this bug is currently being exploited in some libs. Most likely, if it gets fixed, it becomes a warning, and people can opt in making it an error.

**Comment by nodakai** [comment]
```f#
let spanOfOptString(s: Option<string>) =
  match os with Some(s) -> s.AsSpan()
                | None -> raise(Exception())
```

> error FS0412: A type instantiation involves a byref type. This is not permitted by the rules of Common IL.

I had to modify it like this

```f#
let spanOfOptString(os: Option<string>) =
  match os with Some(s) -> s.AsSpan()
                | None -> raise(Exception())
                          Span.op_Implicit Span.Empty
```

https://sharplab.io/#gist:5680a5b7034ea344eb3480d7d53432c6

True bottom type please
