### ISSUE TITLE
subtyping for discriminated unions

### ISSUE THREAD

**Issue by baronfel** [baronfel/fsharp-lang-suggestions-final#359]
# subtyping for discriminated unions [6672490] #

**Submitted by exercitus vir on 11/6/2014 12:00:00 AM**  
**4 votes on UserVoice prior to migration**  

We need be able to explicitly specify (structural) subset relationships of discriminated unions (similar to polymorphic variants in OCaml but defined at type definition). There are many uses cases for this.
For example:
type Superset = A | B | C
//structural subset relation must be explicitly declared, but only in the definition
type Subset :> Superset = A | B
//no need to repeat subset relation because a superset can always handle all cases of any subset
let accept_subset (superset : Superset ) =
match superset with
| A -> "A"
| B -> "B"
| C -> "C"
//it does not matter that A is ambiguous (Superset.A and Subset.A) because subset case would be cast to Superset type anyway
//but it should also be possible to specify Subset.A, which would be cast to the Superset type
let accepted_subset = accept_subset A
let accept_superset (subset : Subset ) =
match subset with
| A -> "A"
| B -> "B"
//it does not matter that A is ambiguous (Superset.A and Subset.A) because superset case would be cast to Subset type anyway
//but it should also be possible to specify Superset.A, which would be cast to the Subset type
let accepted_superset = accept_superset A
This would not break backwards compatibility as it is currently possible to hack this together using explicit static member constraints and additional interfaces (one interface per case), but that is really ugly and repetitive.

## Response ##
** by fslang-admin on 2/5/2016 12:00:00 AM **

Many thanks for the suggestion. I’ve declined it per my comment below, please see what I wrote there
Best wishes
Don Syme, F# Language Evolution

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/6672490)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-6672490-subtyping-for-discriminated-unions.md#comments)

**Comment by kspeakman** [comment]
@dsyme The user voice comments are no longer available. Can you comment on the reason here? I was just about to make a similar suggestion and I have a use case to share.

In my case, a DU represents business events in my system. (Event sourcing) In almost every case then, listeners never do exhaustive matching. They only handle a subset of the events. And these subsets are not able to be organized ahead of time. They tend to be emergent as we implement new features and not exactly matching subsets used by other listeners.

One strategy is instead of using the main event DU (and underscore matching) is to create a local event type representing just the cases handled by the listener. This allows devs to exhaustively match in code as well as avoiding unnecessary IO of loading unhandled events (can generate a filter list from the local type).

The main issue is that the local event type is copy/pasted from the main one. So it is possible for the local and main event types to get out of sync during feature development. (Once we release a feature this is not as much a problem since events are immutable.) Having the ability to create a subset of the main DU would ensure that this issue would result in compile time errors instead of runtime ones.

A large percentage of the event cases have data. Ideally the subset definition could just specify the tag.

This could also be quite useful in MVU applications.

**Comment by smoothdeveloper** [comment]
@kspeakman the uservoice archive: https://github.com/fsharp/fslang-suggestions/blob/d48c35ce216e2bff148937ec028ad61e5c273fdf/archive/suggestion-6672490-subtyping-for-discriminated-unions.md

you can find the link from the readme.md "View all archived uservoice suggestions and comments"

**Comment by kspeakman** [comment]
@smoothdeveloper Thanks. I clicked the link in the issue post and got a 404, so I assumed it was garbage collected.

**Comment by kspeakman** [comment]
After reading the comments, I still believe it merits reconsidering. I don't see the point of record subsets. I frequently deal with records which are subsets of other records. But in those cases the opposite feature would be useful: accreting properties from different records.

The specific example I'm think of is a context object. I have a application context (a record), populated from env vars at startup, which is essentially an accretion of all integration settings. A given integration only requires a subset of them. To make that integration reusable, it declares its own independent context. A subset would not work here, because it would require the integration to take a dependency on the application context and therefore not reusable by other apps.

**Comment by kspeakman** [comment]
P.S. This feature is not of vital importance to me, but I felt I had a practical use case to share. Maybe it will be helpful.
